# Generated by Django 3.0 on 2020-01-28 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120, null=True, verbose_name='Texto da alternativa')),
            ],
        ),
        migrations.CreateModel(
            name='Arvore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True, verbose_name='Nome do Formulário')),
            ],
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True, verbose_name='Nome da Escolha')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do formulário')),
                ('descricao', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descricao')),
                ('data_inicial', models.DateField(null=True, verbose_name='Data de Início')),
                ('data_final', models.DateField(null=True, verbose_name='Data Final')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilGeral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do Perfil')),
                ('numero_de_usuarios', models.PositiveIntegerField(default=0)),
                ('formularios', models.ManyToManyField(blank=True, to='blog.Formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da pergunta')),
                ('pergunta', models.CharField(max_length=120, verbose_name='Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120, null=True, verbose_name='Texto da Question')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True, verbose_name='Nome do Usuário')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('idade', models.IntegerField(null=True)),
                ('genero', models.CharField(choices=[('Masc', 'Masculino'), ('Femin', 'Feminino'), ('Outro', 'Outro')], max_length=15, null=True, verbose_name='Gênero')),
                ('escolaridade', models.CharField(choices=[('FI', 'Ensino Fundamental Incompleto'), ('FC', 'Ensino Fundamental Completo'), ('MI', 'Ensino Medio Incompleto'), ('MC', 'Ensino Medio Completo'), ('SI', 'Ensino Superior Incompleto'), ('SC', 'Ensino Superior Completo')], max_length=3, null=True, verbose_name='Escolaridade')),
                ('curso', models.CharField(max_length=120, null=True, verbose_name='Curso')),
                ('nacionalidade', models.CharField(max_length=120, null=True, verbose_name='Nacionalidade')),
                ('alternativas', models.ManyToManyField(blank=True, to='blog.Alternativa')),
                ('arvores', models.ManyToManyField(blank=True, to='blog.Arvore')),
                ('form_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_atual', to='blog.Formulario')),
                ('formularios', models.ManyToManyField(blank=True, to='blog.Formulario')),
                ('perfil_especifico', models.ForeignKey(editable=False, max_length=120, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.PerfilGeral')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True, verbose_name='Nome da Tela')),
                ('ultimo', models.BooleanField(default=False, verbose_name='É um teste')),
                ('arvore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Arvore')),
                ('question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_data', models.DateField(blank=True, null=True, verbose_name='Data da resposta')),
                ('alternativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Alternativa')),
                ('formulario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Formulario')),
                ('pergunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Pergunta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Raiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tela', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Tela')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tela_filha',
            field=models.ManyToManyField(related_name='tela_filha', through='blog.Escolha', to='blog.Tela'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='perguntas',
            field=models.ManyToManyField(blank=True, to='blog.Pergunta'),
        ),
        migrations.AddField(
            model_name='escolha',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Question'),
        ),
        migrations.AddField(
            model_name='escolha',
            name='tela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Tela'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pergunta'),
        ),
    ]
