# Generated by Django 3.0.2 on 2020-01-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='perguntas',
        ),
        migrations.RemoveField(
            model_name='perfilgeral',
            name='formularios',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='alternativa',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='alternativas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='form_atual',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='formularios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil_especifico',
        ),
        migrations.AddField(
            model_name='resposta',
            name='arvore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Arvore'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='escolha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Escolha'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Question'),
        ),
        migrations.AlterField(
            model_name='arvore',
            name='nome',
            field=models.CharField(max_length=120, null=True, verbose_name='Nome da Árvore'),
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.DeleteModel(
            name='PerfilGeral',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
    ]
