# Generated by Django 3.0.2 on 2020-01-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200128_1509'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='arvore',
            name='submetida',
            field=models.BooleanField(default=False, verbose_name='Já foi submetida à resposta'),
        ),
    ]
  
