# Generated by Django 3.0.2 on 2020-01-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200128_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiz',
            name='tela',
        ),
        migrations.AddField(
            model_name='raiz',
            name='arvore',
            field=models.OneToOneField(blank=True, help_text='<h1><strong>Ao submeter uma árvore a ser respondinda no site, ela não poderá mais ser editada.</strong></h1>', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Arvore'),
        ),
    ]
