# Generated by Django 3.0.2 on 2020-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200128_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estimulos/'),
        ),
    ]
