# Generated by Django 3.0.2 on 2020-01-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tela_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tela',
            name='texto',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
